export { default as AnimatedNumber } from "./AnimateNumber/Number";
export type { AnimatedNumberProps } from "./AnimateNumber/Number";
export { default as Button } from "./Button/Button";
export type { ButtonProps } from "./Button/Button";
export { default as Footer } from "./Footer/Footer";
export { default as Hero } from "./Hero/Hero";
export { default as Logo } from "./Logo/Logo";
export type { LogoProps } from "./Logo/Logo";
export { default as Marker } from "./Navbar/Marker";
export type { MarkerProps } from "./Navbar/Marker";
export { ConstNavbar, default as Navbar } from "./Navbar/Navbar";
export { default as TeamCard } from "./TeamCard/TeamCard";
export type { TeamCardProps } from "./TeamCard/TeamCard";